#
# Call it with java-versions like:
#
# jobs:
#  call-ci:
#    uses: tomasbjerre/.github/.github/workflows/bundle-gradle-ci.yaml@master
#    with:
#      java-versions: '["17", "21"]'
#
#
name: Bundle Gradle CI

on:
  workflow_call:
    inputs:
      java-versions:
        description: "Java versions to test against"
        required: false
        default: '["17", "21", "25"]'
        type: string

jobs:
  call-gradle-ci:
    uses: tomasbjerre/.github/.github/workflows/gradle-ci.yaml@master
    with:
      java-versions: ${{ inputs.java-versions }}
  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    uses: tomasbjerre/.github/.github/workflows/publish-release-on-tag-push.yaml@master
