name: Git Changelog Github Release

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: tomasbjerre/.github/.github/actions/publish-github-release@master
        with:
          draft: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
