name: Bundle Gradle CI

on: [workflow_call]

jobs:
  call-gradle-ci:
    uses: tomasbjerre/.github/.github/workflows/gradle-ci.yaml@master
  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    uses: tomasbjerre/.github/.github/workflows/publish-release-on-tag-push.yaml@master
