name: Gradle Release

on: [workflow_call]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: "true"
          fetch-depth: "0"

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "zulu"

      - name: Publish with Gradle
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "nobody@fk.se"
          ./gradlew updateVersion && ./gradlew release
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
