name: Gradle CI

on: [workflow_call, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      #max-parallel: 3
      fail-fast: false
      matrix:
        java: [ '11', '8', '17' ] # 11 does static code analysis, so run it first
        #os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        os: [ 'ubuntu-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: "Setup Git"
        shell: bash
        run: |
          git branch -a
          for branch in $(
            git branch -a \
              | grep '^\s*remotes' \
              | egrep --invert-match '(:?HEAD|remotes/pull/[0-9]+/merge)$' \
              | sed -e "s/^.*remotes\/origin\///"
          ); do
              echo setting up $branch
              git checkout $branch
              git checkout -
          done
          git branch -a
          git remote remove origin
          git remote add origin git@github.com:${GITHUB_REPOSITORY}.git
          git remote -v
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: prepare Gradle
        shell: bash
        run: |
          mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - name: Check formatting
        if: ${{ matrix.java == '11' }}
        shell: bash
        run: |
          ./gradlew --no-daemon -s -x googleJavaFormat verifyGoogleJavaFormat
      - name: "Gradle build"
        shell: bash
        run: |
          java -version
          javac -version
          ./gradlew --no-daemon build -s

      - name: Transorm static code analysis to SARIF
        if: ${{ (success() || failure()) }}
        run: |
          npx violations-command-line -sarif sarif-report.json \
          -v "FINDBUGS" "." ".*spotbugs/main\.xml$" "Spotbugs" \
          -v "CHECKSTYLE" "." ".*checkstyle/main\.xml$" "Checkstyle" \
          -v "PMD" "." ".*pmd/main\.xml$" "PMD" \
          -v "JUNIT" "." ".*test/TEST-.*\.xml$" "JUNIT"
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ (success() || failure()) }}
        with:
          sarif_file: sarif-report.json

      - name: Publish Build
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.java }}
          path: ${{ github.workspace }}
