name: Gradle CI

on: [workflow_call, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '8', '11' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: prepare Gradle
        run: mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - run: ./gradlew --no-daemon build -s
      - name: Publish Build
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.java }}
          path: ${{ github.workspace }}
  static-code-analysis:
    if: ${{ github.head_ref != github.base_ref }} # if it is a PR build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: prepare Gradle
        run: mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - name: check
        run: ./gradlew --no-daemon build -xtest -xgoogleJavaFormat
      - name: create template
        run: |
          VIOLATION_TEMPLATE=$(cat << EOF
          {{violation.message}}
          EOF
          )
          echo "VIOLATION_TEMPLATE<<EOF" >> $GITHUB_ENV
          echo "$VIOLATION_TEMPLATE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Spotbugs
        uses: tomasbjerre/violation-comments-action@master
        with:
          parser: FINDBUGS
          regexp: '.*spotbugs/main\.xml$'
          keepOldComments: false
          commentTemplate: ${{ env.VIOLATION_TEMPLATE }}
      - name: Checkstyle
        uses: tomasbjerre/violation-comments-action@master
        with:
          parser: CHECKSTYLE
          regexp: '.*checkstyle/main\.xml$'
          keepOldComments: true
          commentTemplate: ${{ env.VIOLATION_TEMPLATE }}
      - name: PMD
        uses: tomasbjerre/violation-comments-action@master
        with:
          parser: PMD
          regexp: '.*pmd/main\.xml$'
          keepOldComments: true
          commentTemplate: ${{ env.VIOLATION_TEMPLATE }}

