name: Publish release on tag push

on: [workflow_call]

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: "true"
          fetch-depth: "0"

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "zulu"

      - uses: tomasbjerre/git-changelog-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
