name: Publish release on tag push

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: "0"
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 17
      - uses: tomasbjerre/git-changelog-github-release@main
        with:
          draft: false
