name: Publish release on tag push

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: tomasbjerre/.github/.github/actions/publish-github-release@master
        with:
          draft: "false"
          github-token: ${{ secrets.GITHUB_TOKEN }}
